export const ErrorCode = {
  AUTH_REQUIRED: 'AUTH_REQUIRED',
  INVALID_TOKEN: 'INVALID_TOKEN',
  TENANT_NOT_FOUND: 'TENANT_NOT_FOUND',
  FORBIDDEN_MODULE: 'FORBIDDEN_MODULE',
  FORBIDDEN_PERMISSION: 'FORBIDDEN_PERMISSION',
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  USER_INACTIVE: 'USER_INACTIVE',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
} as const;

export type ErrorCode = (typeof ErrorCode)[keyof typeof ErrorCode];
