export const ErrorCode = {
  AUTH_REQUIRED: 'AUTH_REQUIRED',
  INVALID_TOKEN: 'INVALID_TOKEN',
  SESSION_EXPIRED: 'SESSION_EXPIRED',
  CLIENT_UPGRADE_REQUIRED: 'CLIENT_UPGRADE_REQUIRED',
  TENANT_NOT_FOUND: 'TENANT_NOT_FOUND',
  FORBIDDEN_MODULE: 'FORBIDDEN_MODULE',
  FORBIDDEN_PERMISSION: 'FORBIDDEN_PERMISSION',
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  USER_INACTIVE: 'USER_INACTIVE',
  RATE_LIMITED: 'RATE_LIMITED',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
} as const;


export type ErrorCode = (typeof ErrorCode)[keyof typeof ErrorCode];
