// Writes the build identity before every build/serve/test:
//  - src/app/core/version/build-info.generated.ts  (compiled into the app: "which version am I")
//  - public/version.json                            (served no-cache: "which version is deployed")
// Both are generated (gitignored). Release notes and the "critical release" flags live in the
// committed release.json, edited by hand when a release needs them.
import { execSync } from 'node:child_process';
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname } from 'node:path';

const root = new URL('../', import.meta.url);
const pkg = JSON.parse(readFileSync(new URL('package.json', root), 'utf8'));
let release = {};
try {
  release = JSON.parse(readFileSync(new URL('release.json', root), 'utf8'));
} catch {
  release = {};
}

let commit = 'local';
try {
  commit = execSync('git rev-parse --short HEAD', { cwd: root, stdio: ['ignore', 'pipe', 'ignore'] }).toString().trim();
} catch {
  // not a git checkout (e.g. CI tarball): keep "local"
}
const builtAt = new Date().toISOString();
const info = {
  version: pkg.version,
  commit,
  builtAt,
  buildId: `${pkg.version}+${commit}.${builtAt.replace(/\D/g, '').slice(0, 12)}`,
  notes: typeof release.notes === 'string' ? release.notes : '',
  forceLogout: release.forceLogout === true,
  minVersion: typeof release.minVersion === 'string' ? release.minVersion : null,
};

const write = (relative, content) => {
  const target = new URL(relative, root);
  mkdirSync(dirname(target.pathname.replace(/^\/([A-Za-z]:)/, '$1')), { recursive: true });
  writeFileSync(target, content);
};
write('public/version.json', JSON.stringify(info, null, 2) + '\n');
write(
  'src/app/core/version/build-info.generated.ts',
  `// Generated by scripts/write-version.mjs — do not edit.\nimport type { BuildInfo } from './build-info';\n\nexport const BUILD_INFO: BuildInfo = ${JSON.stringify(info, null, 2)};\n`,
);
console.log(`build ${info.buildId}${info.forceLogout ? ' (forceLogout)' : ''}`);
